<?php

declare(strict_types=1);

/*
|--------------------------------------------------------------------------
| Brand registry
|--------------------------------------------------------------------------
|
| The eight candidate identities from §105 of the master spec. The active one
| drives the `data-brand` attribute on <html>, the favicon set, the logo
| lockups and — through resources/css/brands.css — every primary colour in the
| product.
|
| Switching brands is a config change. Nothing in application code may branch
| on a brand key.
|
| Assets for each brand live in public/brand/<key>/ and are generated by
| `node scripts/brand/generate.mjs`. See resources/brand/README.md.
|
| None of these names has been cleared for trademark, company name, social
| handle or domain availability (§105.1). Do that before committing publicly.
|
*/

return [

    /*
    |--------------------------------------------------------------------------
    | Active brand
    |--------------------------------------------------------------------------
    |
    | Must be a key in the `brands` array below. Users with permission may
    | preview others at /brand without changing this default.
    |
    */

    'active' => env('BRAND_KEY', 'revora'),

    /*
    |--------------------------------------------------------------------------
    | Allow live preview
    |--------------------------------------------------------------------------
    |
    | When true, the /brand picker can override the active brand for the
    | current session. Intended for choosing a final identity; turn it off
    | once the brand is settled.
    |
    */

    'allow_preview' => (bool) env('BRAND_PREVIEW', true),

    /*
    |--------------------------------------------------------------------------
    | Candidates
    |--------------------------------------------------------------------------
    |
    | `primary`, `secondary` and `accent` mirror §106.3 and exist so the server
    | can emit a theme-colour meta tag and brand transactional email without
    | parsing CSS. The authoritative ramps live in resources/css/brands.css.
    |
    */

    'brands' => [

        'leadora' => [
            'name' => 'Leadora',
            'tagline' => 'Turn Every Lead Into Opportunity.',
            'concept' => 'Abstract L with a forward-moving foot, plus an AI spark.',
            'primary' => '#4F46E5',
            'secondary' => '#2563EB',
            'accent' => '#06B6D4',
        ],

        'leadpulse' => [
            'name' => 'LeadPulse',
            'tagline' => 'More Leads. Higher Conversions.',
            'concept' => 'Heartbeat waveform — lead activity as a real-time signal.',
            'primary' => '#0F766E',
            'secondary' => '#14B8A6',
            'accent' => '#2563EB',
        ],

        'leadminds' => [
            'name' => 'LeadMinds',
            'tagline' => 'Smarter Leads. Better Decisions.',
            'concept' => 'Head silhouette holding a knocked-out node network.',
            'primary' => '#4F46E5',
            'secondary' => '#7C3AED',
            'accent' => '#A855F7',
        ],

        'leadflow' => [
            'name' => 'LeadFlow',
            'tagline' => 'Capture. Nurture. Convert.',
            'concept' => 'Three staggered streaks moving toward conversion.',
            'primary' => '#2563EB',
            'secondary' => '#0EA5E9',
            'accent' => '#10B981',
        ],

        'revora' => [
            'name' => 'Revora',
            'tagline' => 'Grow Faster. Generate More Revenue.',
            'concept' => 'Rising revenue bars with a trend arrow clearing the tops.',
            'primary' => '#059669',
            'secondary' => '#10B981',
            'accent' => '#2563EB',
        ],

        'leadforge' => [
            'name' => 'LeadForge',
            'tagline' => 'Turn Interest Into Impact.',
            'concept' => 'Slanted geometric F — raw interest forged into opportunity.',
            'primary' => '#EA580C',
            'secondary' => '#F97316',
            'accent' => '#EF4444',
        ],

        'leadorbit' => [
            'name' => 'LeadOrbit',
            'tagline' => 'Connect. Engage. Grow.',
            'concept' => 'Opportunity node inside an orbital ring.',
            'primary' => '#6D28D9',
            'secondary' => '#7C3AED',
            'accent' => '#4F46E5',
        ],

        'leadnest' => [
            'name' => 'LeadNest',
            'tagline' => 'Your Leads. Our Priority.',
            'concept' => 'Leaf-cradle holding three ascending leads.',
            'primary' => '#059669',
            'secondary' => '#0D9488',
            'accent' => '#14B8A6',
        ],

    ],

];
